name: Publish to WinGet

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Submit to WinGet
        uses: vedantmgoyal9/winget-releaser@4ffc7888bffd451b357355dc214d43bb9f23917e # v2
        with:
          identifier: ToddWhitehead.PTG
          installers-regex: 'win-x64\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
